batch_size: 64
epochs: 80
lr: 0.001

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data

# Transformer Model specific configurations
transformer_model_name: bert-base-uncased  # Transformer model to be used

# Evaluation
model_path: 